version: 2.1
jobs:
  build_and_deploy:     
    docker:
        - image: google/cloud-sdk:slim
    steps:
      - checkout
      - run:
          name: Install Env
          command: |
            apt install -y python-pip && \
            pip freeze > requirements.txt
            python3 -m pip install -r requirements.txt
      - run: 
          name: Deploy to Google Engine
          command: |
            echo ${GOOGLE_PROJECT_ID}
            echo ${GOOGLE_COMPUTE_ZONE}
            echo ${GCLOUD_SERVICE_KEY} > /tmp/sa_key.json
            gcloud auth activate-service-account --key-file=/tmp/sa_key.json
            rm /tmp/sa_key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet app deploy
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
        filters:
          branches:
            only:
              - main